spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 592452468790-0esp77q9eh3nmcn9f370qa1b6h9f10i3.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          facebook:
            clientId: 4980115898738616
            clientSecret: cd323bc18783789c21ce3333301cdb47
            scope:
              - email
              - public_profile
server:
  port: 8080